# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
          version: 18.06.0-ce


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "req.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r req.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "req.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ls
            python manage.py test

#       - run:
#           name: Install Docker client
#           command: |
#             set -x
#             VER="17.03.0-ce"
#             wget -P /tmp -L https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#             tar -xvzf /tmp/docker-$VER.tgz -C /tmp 
#             sudo mv -f /tmp/docker/docker* /usr/bin
#             sudo mv -f /tmp/docker/completion/bash/*  /usr/bin/completion/bash/
#             sudo mv -f /tmp/docker/completion/fish/*  /usr/bin/completion/fish/
#             sudo mv -f /tmp/docker/completion/zsh/*  /usr/bin/completion/zsh/
            
#       - run:
#          name: Build Docker image
#          command: |
#             sudo dockerd
#             sudo docker build -t hello_world .
#        - run:
#           name: Push to DockerHub
#           command: |
#             sudo docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
#             sudo docker push formage/InstaBUG_hello_world


      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            sudo tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin   

      - run: 
          name: Build docker image
          command: |
            TAG=$CIRCLE_BUILD_NUM
            docker build -t   formage/instabug_demo_docker:$TAG .    


      - run: 
          name: Push to dockerhub
          command: |
            TAG=$CIRCLE_BUILD_NUM
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD    
            docker push formage/instabug_demo_docker:$TAG



