# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
<<<<<<< HEAD
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:4.8.2 # the primary container, where your job's commands are run
=======
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

>>>>>>> 228946c40d92ce6c6a1cb531bb624b6b3a8e6b3d
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "req.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r req.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "req.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

<<<<<<< HEAD
=======
      - store_artifacts:
          path: test-reports
          destination: test-reports
>>>>>>> 228946c40d92ce6c6a1cb531bb624b6b3a8e6b3d
